apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-3-rootapplication
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/openshift-ai-app-of-apps'
    targetRevision: main
    path: clusters/ocpai3
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    syncOptions:
      - ApplyOutOfSyncOnly=true
