apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Ensure this deploys after any future "cluster-basics" bundles if you add them.
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/openshift-ai-app-of-apps'
    targetRevision: main
    path: components/operators/metal-lb/base
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    syncOptions:
      # Let Argo create the target namespace for MinIO.
      - CreateNamespace=true
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
